import type { EasyPayState, User } from './types';

export const onboardData = [
  { t: 'Pay anyone,\nin one scan.', b: 'Scan any UPI QR and send money instantly — no account numbers, no waiting.' },
  { t: 'Your money,\nfully in control.', b: 'Track every rupee. Confirm each payment yourself so your history stays honest.' },
  { t: 'Powered by\nthe apps you trust.', b: 'Pay through Google Pay over UPI, right from EasyPay. Fast, familiar, secure.' },
];

export const debugUser: User = {
  name: 'Test User',
  phone: '90000 00000',
  email: 'test.user@easypay.dev',
  bank: 'Demo Bank',
};

export const initialState: EasyPayState = {
  screen: 'onboard',
  isAuthenticated: false,
  onboardIndex: 0,
  authMode: 'signup',
  authPhone: '',
  suName: '',
  suEmail: '',
  suBank: '',
  user: { name: '', phone: '', email: '', bank: '' },
  balance: 0,
  cameraFallback: false,
  upiValue: '',
  noteValue: '',
  amount: '',
  isAmountFixed: false,
  payee: null,
  showConfirm: false,
  selectedBudgetId: null,
  showAddBalance: false,
  addAmount: '',
  showBudgetPicker: false,
  showCreateBudget: false,
  newBudgetName: '',
  newBudgetAmt: '',
  newBudgetIcon: 'food',
  budgets: [
    { id: 'b_groceries', name: 'Groceries', allocated: 0, icon: 'food', frozen: false },
    { id: 'b_fuel', name: 'Fuel', allocated: 0, icon: 'transit', frozen: false },
    { id: 'b_dining', name: 'Dining', allocated: 0, icon: 'food', frozen: false },
    { id: 'b_shopping', name: 'Shopping', allocated: 0, icon: 'shop', frozen: true },
    { id: 'b_rent', name: 'Rent', allocated: 0, icon: 'home', frozen: false },
    { id: 'b_utilities', name: 'Utilities', allocated: 0, icon: 'bills', frozen: false },
    { id: 'b_entertainment', name: 'Entertainment', allocated: 0, icon: 'fun', frozen: false },
    { id: 'b_travel', name: 'Travel', allocated: 0, icon: 'transit', frozen: false },
    { id: 'b_investments', name: 'Investments', allocated: 0, icon: 'misc', frozen: false },
    { id: 'b_emergency', name: 'Emergency Fund', allocated: 0, icon: 'health', frozen: false },
  ],
  txns: [],
  showEditProfile: false,
  editName: '',
  editPhone: '',
  editEmail: '',
  editBank: '',
  editingBudgetId: null,
  showMyQr: false,
  showOverBudget: false,
  showOverFrozen: false,
  overBudgetId: null,
  overFrozenId: null,
  obDeficit: 0,
  showTransferPicker: false,
  wishlist: [
    { id: 'w1', name: 'Vacation', targetAmt: 50000, currentAmt: 10000, priority: 'P1', deadline: 'Dec 2026', image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=400&q=80' },
    { id: 'w2', name: 'Laptop', targetAmt: 120000, currentAmt: 30000, priority: 'P2', deadline: 'Aug 2026', image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=400&q=80' },
    { id: 'w3', name: 'Emergency Fund', targetAmt: 300000, currentAmt: 150000, priority: 'P1', deadline: 'Ongoing', image: 'https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?auto=format&fit=crop&w=400&q=80' },
  ],
  subscriptions: [
    { id: 's1', name: 'Netflix', icon: '🍿', amount: 649, cadence: { type: 'monthly' }, annualCost: 7788, lastUsed: 'Yesterday', cancelSuggested: false },
    { id: 's2', name: 'Gym', icon: '🏋️', amount: 1500, cadence: { type: 'monthly' }, annualCost: 18000, lastUsed: '2 weeks ago', cancelSuggested: true },
  ],
  merchants: [
    { id: 'm1', name: 'Starbucks', visits: 12, monthlyTotal: 1320, averageBill: 410, trend: 'up' },
    { id: 'm2', name: 'Amazon', visits: 5, monthlyTotal: 4500, averageBill: 900, trend: 'stable' },
  ],
  showCreateSubscription: false,
  newSubName: '',
  newSubIcon: '💳',
  newSubAmount: '',
  newSubCadenceType: 'monthly',
  newSubCadenceInterval: '1',
  newSubCadenceUnit: 'month',
  defaultPaymentApp: 'upi',
  showAppPicker: false,
};
